services:
  backend:
    build: ./backend
    ports:
      - "3000:3000" 
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
